# Generated by Django 5.2.14 on 2026-05-10 06:06
# 手動編集: FK フィールドを設計の順序に並び替え。
# StockReservation を OutboundOrderItem より先に CreateModel し、reservation を fields に組み込む

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbound', '0001_initial'),
        ('masters', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_order_code', models.CharField(max_length=30, unique=True, verbose_name='出荷指示番号')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse', verbose_name='倉庫')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer', verbose_name='顧客')),
                ('external_order_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='OMS注文番号')),
                ('delivery_postal_code', models.CharField(blank=True, max_length=10, verbose_name='配送先郵便番号')),
                ('delivery_address', models.CharField(blank=True, max_length=255, verbose_name='配送先住所')),
                ('delivery_name', models.CharField(blank=True, max_length=100, verbose_name='配送先名称')),
                ('status', models.CharField(choices=[('pending', '出荷待ち'), ('picking', 'ピッキング中'), ('inspecting', '検品・梱包・送り状貼付中'), ('shipped', '出荷済み'), ('cancelled', '取消')], default='pending', max_length=20, verbose_name='ステータス')),
                ('source_type', models.CharField(choices=[('oms', 'OMS取り込み'), ('manual', '手動登録'), ('return', '返品出荷')], default='oms', max_length=20, verbose_name='出荷元種別')),
                ('priority', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='優先度')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='出荷期限')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='出荷日時')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消日時')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_outbound_orders', to=settings.AUTH_USER_MODEL, verbose_name='取消実施者')),
                ('cancel_reason', models.CharField(blank=True, choices=[('stock_shortage', '在庫不足'), ('damage', '破損'), ('manual', '運用判断'), ('oms_request', 'OMS要求')], max_length=20, null=True, verbose_name='取消理由')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_outbound_orders', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '出荷指示',
                'verbose_name_plural': '出荷指示',
                'db_table': 'outbound_orders',
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.location', verbose_name='ロケーション')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.sku', verbose_name='SKU')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='引き当て数')),
                ('status', models.CharField(choices=[('active', '引き当て中'), ('released', '解放済み'), ('expired', '期限切れ')], default='active', max_length=20, verbose_name='ステータス')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='outbound.outboundorder', verbose_name='出荷指示')),
                ('inbound_order_item', models.ForeignKey(blank=True, help_text='ASN引き当ての場合のみセット', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inbound.inboundorderitem', verbose_name='紐づく入荷予定明細')),
                ('is_crossdock', models.BooleanField(default=False, verbose_name='クロスドック')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='有効期限')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='解放日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '在庫引き当て',
                'verbose_name_plural': '在庫引き当て',
                'db_table': 'stock_reservations',
            },
        ),
        migrations.CreateModel(
            name='OutboundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outbound.outboundorder', verbose_name='出荷指示')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.sku', verbose_name='SKU')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.location', verbose_name='ピッキング元ロケーション')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outbound.stockreservation', verbose_name='紐づく引き当て')),
                ('quantity_ordered', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='指示数量')),
                ('quantity_shipped', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='実出荷数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '出荷指示明細',
                'verbose_name_plural': '出荷指示明細',
                'db_table': 'outbound_order_items',
            },
        ),
        migrations.CreateModel(
            name='PickingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picking_list_code', models.CharField(max_length=30, unique=True, verbose_name='ピッキングリスト番号')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse', verbose_name='倉庫')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.area', verbose_name='対象エリア')),
                ('picking_type', models.CharField(choices=[('order', 'オーダーピッキング'), ('total', '種まき方式（AGV/GTP）'), ('zone', 'ゾーンピッキング')], default='order', max_length=20, verbose_name='ピッキング種別')),
                ('status', models.CharField(choices=[('pending', '未生成'), ('in_progress', '作業中'), ('completed', '完了'), ('cancelled', '取消')], default='pending', max_length=20, verbose_name='ステータス')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_picking_lists', to=settings.AUTH_USER_MODEL, verbose_name='担当作業者')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_picking_lists', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ピッキングリスト',
                'verbose_name_plural': 'ピッキングリスト',
                'db_table': 'picking_lists',
            },
        ),
        migrations.CreateModel(
            name='PickingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picking_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='outbound.pickinglist', verbose_name='ピッキングリスト')),
                ('outbound_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outbound.outboundorderitem', verbose_name='出荷指示明細')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.location', verbose_name='ピッキング元')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.sku', verbose_name='SKU')),
                ('quantity_requested', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='指示数量')),
                ('quantity_picked', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='実ピッキング数')),
                ('status', models.CharField(choices=[('pending', '未生成'), ('picking', '作業中'), ('picked', '完了'), ('short', '欠品'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ピッキング担当者')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('sort_order', models.IntegerField(blank=True, help_text='order タイプのみ有効。棚番順', null=True, verbose_name='ソート順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ピッキング明細',
                'verbose_name_plural': 'ピッキング明細',
                'db_table': 'picking_list_items',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_code', models.CharField(max_length=30, unique=True, verbose_name='出荷番号')),
                ('outbound_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='outbound.outboundorder', verbose_name='出荷指示')),
                ('status', models.CharField(choices=[('inspecting', '検品・梱包・送り状貼付中'), ('ready', '出荷準備完了'), ('shipped', '出荷済み')], default='inspecting', max_length=20, verbose_name='ステータス')),
                ('carrier_name', models.CharField(blank=True, help_text='例: ヤマト運輸', max_length=100, verbose_name='運送会社名')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='追跡番号')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='出荷日時')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_shipments', to=settings.AUTH_USER_MODEL, verbose_name='検品担当者')),
                ('inspected_at', models.DateTimeField(blank=True, null=True, verbose_name='検品完了日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '出荷実績',
                'verbose_name_plural': '出荷実績',
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='outbound.shipment', verbose_name='出荷')),
                ('outbound_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outbound.outboundorderitem', verbose_name='出荷指示明細')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.sku', verbose_name='SKU')),
                ('quantity_shipped', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='出荷数量')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stockmovement', verbose_name='紐づく出庫履歴')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '出荷実績明細',
                'verbose_name_plural': '出荷実績明細',
                'db_table': 'shipment_items',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note_code', models.CharField(max_length=30, unique=True, verbose_name='納品書番号')),
                ('outbound_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='outbound.outboundorder', verbose_name='出荷指示')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.customer', verbose_name='顧客')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='発行日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '納品書',
                'verbose_name_plural': '納品書',
                'db_table': 'delivery_notes',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='outbound.deliverynote', verbose_name='納品書')),
                ('outbound_order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='outbound.outboundorderitem', verbose_name='出荷指示明細')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.sku', verbose_name='SKU')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名（スナップショット）')),
                ('sku_code', models.CharField(max_length=50, verbose_name='SKUコード（スナップショット）')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '納品書明細',
                'verbose_name_plural': '納品書明細',
                'db_table': 'delivery_note_items',
            },
        ),
        migrations.AddIndex(
            model_name='outboundorder',
            index=models.Index(fields=['status'], name='idx_outbound_orders_status'),
        ),
        migrations.AddIndex(
            model_name='outboundorder',
            index=models.Index(fields=['deadline_at'], name='idx_outbound_orders_deadline'),
        ),
        migrations.AddIndex(
            model_name='pickinglist',
            index=models.Index(fields=['status'], name='idx_picking_lists_status'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='idx_shipments_status'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['shipped_at'], name='idx_shipments_shipped_at'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.UniqueConstraint(fields=('shipment', 'sku'), name='uk_shipment_items_shipment_sku'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['location', 'sku', 'status'], name='idx_reservations_lss'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['status'], name='idx_reservations_status'),
        ),
        migrations.AddConstraint(
            model_name='outboundorderitem',
            constraint=models.UniqueConstraint(fields=('outbound_order', 'sku', 'location'), name='uk_outbound_order_items_osl'),
        ),
    ]
