# Generated by Django 5.2.14 on 2026-05-17 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作業開始日時'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='in_progress_by',
            field=models.ForeignKey(blank=True, help_text='検品・梱包の作業中の担当者。NULL=作業中でない（開始で設定、完了で解除）。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_in_progress', to=settings.AUTH_USER_MODEL, verbose_name='作業担当者'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='status',
            field=models.CharField(choices=[('picking_wait', 'ピッキング作業待ち'), ('inspection_wait', '出荷検品作業待ち'), ('shipped', '出荷完了'), ('cancelled', '取消')], default='picking_wait', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='inspected_by',
            field=models.ForeignKey(blank=True, help_text='検品・梱包を完了した担当者の記録（完了時に設定）。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_shipments', to=settings.AUTH_USER_MODEL, verbose_name='検品担当者'),
        ),
    ]
