# Generated by Django 5.2.14 on 2026-05-17 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_remove_category_category_name_en_and_more'),
        ('outbound', '0002_align_status_and_shipment_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundorderitem',
            name='location',
            field=models.ForeignKey(blank=True, help_text='出荷起動の在庫引き当てで確定する（登録時は NULL）。', null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.location', verbose_name='ピッキング元ロケーション'),
        ),
    ]
