# Generated by Django 5.2.14 on 2026-05-17 02:22

from django.db import migrations, models


def remap_picking_wait_to_allocation_wait(apps, schema_editor):
    """allocation_wait 追加前に登録された出荷指示を allocation_wait に直す。

    出荷起動の実装前は picking_wait の指示はすべて「登録済み・未起動」なので、
    新設の allocation_wait（出荷起動待ち）へ移す。
    """
    OutboundOrder = apps.get_model('outbound', 'OutboundOrder')
    OutboundOrder.objects.filter(status='picking_wait').update(
        status='allocation_wait'
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0003_outbounditem_location_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundorder',
            name='status',
            field=models.CharField(choices=[('allocation_wait', '出荷起動待ち'), ('picking_wait', 'ピッキング作業待ち'), ('inspection_wait', '出荷検品作業待ち'), ('shipped', '出荷完了'), ('cancelled', '取消')], default='allocation_wait', max_length=20, verbose_name='ステータス'),
        ),
        migrations.RunPython(remap_picking_wait_to_allocation_wait, noop),
    ]
