# Generated by Django 5.2.14 on 2026-05-21 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_inspected_at(apps, schema_editor):
    """既に SHIPPED な指示の明細は inspected_at = order.shipped_at として埋める。

    per-item 検品モデルの後追い導入のため、過去データの整合性を保つ。
    SHIPPED 以外（allocation_wait / picking_wait / inspection_wait / cancelled）
    は inspected_at を NULL のまま残し、将来検品が走る時に per-item で埋める。
    """
    OutboundOrder = apps.get_model('outbound', 'OutboundOrder')
    OutboundOrderItem = apps.get_model('outbound', 'OutboundOrderItem')
    shipped = OutboundOrder.objects.filter(status='shipped').values('pk', 'shipped_at')
    for order in shipped:
        OutboundOrderItem.objects.filter(
            outbound_order_id=order['pk'], inspected_at__isnull=True,
        ).update(inspected_at=order['shipped_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0004_outboundorder_allocation_wait'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundorderitem',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='検品完了日時'),
        ),
        migrations.AddField(
            model_name='outboundorderitem',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_outbound_order_items', to=settings.AUTH_USER_MODEL, verbose_name='検品担当者'),
        ),
        migrations.RunPython(backfill_inspected_at, migrations.RunPython.noop),
    ]
