# Generated by Django 5.2.14 on 2026-05-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0005_add_oo_item_inspected_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickinglist',
            name='status',
            field=models.CharField(choices=[('pending', '未着手'), ('in_progress', '作業中'), ('completed', '完了'), ('cancelled', '取消')], default='pending', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='pickinglistitem',
            name='status',
            field=models.CharField(choices=[('pending', '未着手'), ('picking', '作業中'), ('picked', '完了'), ('short', '欠品'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス'),
        ),
    ]
