# Generated by Django 5.2.14 on 2026-05-22 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0006_alter_pickinglist_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverynote',
            options={'verbose_name': '出荷明細書', 'verbose_name_plural': '出荷明細書'},
        ),
        migrations.AlterModelOptions(
            name='deliverynoteitem',
            options={'verbose_name': '出荷明細書明細', 'verbose_name_plural': '出荷明細書明細'},
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='delivery_note_code',
            field=models.CharField(max_length=30, unique=True, verbose_name='出荷明細書番号'),
        ),
        migrations.AlterField(
            model_name='deliverynoteitem',
            name='delivery_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='outbound.deliverynote', verbose_name='出荷明細書'),
        ),
    ]
