# Generated by Django 5.2.14 on 2026-05-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0007_alter_deliverynote_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundorder',
            name='priority',
        ),
    ]
