# Generated by Django 5.2.14 on 2026-07-28 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_rename_storage_areas_to_agv'),
        ('outbound', '0008_remove_outboundorder_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='outboundorder',
            index=models.Index(fields=['status', '-created_at'], name='idx_oo_status_created'),
        ),
        migrations.AddIndex(
            model_name='pickinglist',
            index=models.Index(fields=['status', '-created_at'], name='idx_pl_status_created'),
        ),
    ]
