# Generated by Django 5.2.14 on 2026-05-10 06:06
# 手動編集: FK フィールドを設計の順序に並び替え

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.location', verbose_name='ロケーション')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.sku', verbose_name='SKU')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='在庫数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '在庫',
                'verbose_name_plural': '在庫',
                'db_table': 'stock_balances',
                'constraints': [models.UniqueConstraint(fields=('location', 'sku'), name='uk_stock_balances_location_sku'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='chk_stock_balances_quantity')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', '入庫'), ('OUT', '出庫'), ('ADJ', '棚卸調整')], max_length=10, verbose_name='種別')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.location', verbose_name='ロケーション')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.sku', verbose_name='SKU')),
                ('quantity', models.IntegerField(help_text='OUT/ADJ減の場合は負の値で記録', verbose_name='数量')),
                ('quantity_before', models.IntegerField(verbose_name='変動前在庫数')),
                ('quantity_after', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='変動後在庫数')),
                ('reference_type', models.CharField(blank=True, choices=[('inbound_order', '入荷指示'), ('outbound_order', '出荷指示'), ('stock_transfer', '棚間移動'), ('stocktake', '棚卸'), ('manual_in', '計画外入庫'), ('manual_out', '計画外出庫')], max_length=20, null=True, verbose_name='伝票種別')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='伝票ID')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('moved_at', models.DateTimeField(auto_now_add=True, verbose_name='移動日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '入出庫履歴',
                'verbose_name_plural': '入出庫履歴',
                'db_table': 'stock_movements',
                'indexes': [models.Index(fields=['sku', '-moved_at'], name='idx_movements_sku_moved'), models.Index(fields=['movement_type'], name='idx_movements_type'), models.Index(fields=['reference_type', 'reference_id'], name='idx_movements_reference')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='chk_stock_movements_quantity_nonzero'), models.CheckConstraint(condition=models.Q(('quantity_after__gte', 0)), name='chk_stock_movements_quantity_after')],
            },
        ),
    ]
