# Generated by Django 5.2.14 on 2026-05-17 11:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_remove_category_category_name_en_and_more'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='移動数')),
                ('status', models.CharField(choices=[('completed', '完了'), ('cancelled', '取消')], default='completed', max_length=20, verbose_name='ステータス')),
                ('transferred_at', models.DateTimeField(blank=True, null=True, verbose_name='移動日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='masters.location', verbose_name='移動元ロケーション')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.sku', verbose_name='SKU')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='masters.location', verbose_name='移動先ロケーション')),
            ],
            options={
                'verbose_name': '棚間移動',
                'verbose_name_plural': '棚間移動',
                'db_table': 'stock_transfers',
                'indexes': [models.Index(fields=['-transferred_at'], name='idx_stock_transfers_at')],
            },
        ),
    ]
