# Generated by Django 5.2.14 on 2026-05-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stocktransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('inbound_order', '入荷指示'), ('outbound_order', '出荷指示'), ('stock_transfer', '棚間移動'), ('stocktake', '棚卸'), ('manual_in', '計画外入庫'), ('manual_out', '計画外出庫')], max_length=20, null=True, verbose_name='作業内容'),
        ),
    ]
