# Generated by Django 5.2.14 on 2026-05-20 10:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_remove_category_category_name_en_and_more'),
        ('stock', '0003_alter_stockmovement_reference_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StocktakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.IntegerField(help_text='棚卸開始時点の StockBalance.quantity のスナップショット', validators=[django.core.validators.MinValueValidator(0)], verbose_name='帳簿数')),
                ('counted_quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='実カウント数')),
                ('status', models.CharField(choices=[('uncounted', '未カウント'), ('counted', 'カウント済'), ('adjusted', '調整済')], default='uncounted', max_length=20, verbose_name='ステータス')),
                ('counted_at', models.DateTimeField(blank=True, null=True, verbose_name='カウント日時')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_stocktake_items', to=settings.AUTH_USER_MODEL, verbose_name='カウント担当者')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.location', verbose_name='ロケーション')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '棚卸明細',
                'verbose_name_plural': '棚卸明細',
                'db_table': 'stocktake_items',
            },
        ),
        migrations.CreateModel(
            name='StocktakeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('stock_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_adjustment', to='stock.stockmovement', verbose_name='在庫変動')),
                ('stocktake_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment', to='stock.stocktakeitem', verbose_name='棚卸明細')),
            ],
            options={
                'verbose_name': '棚卸調整',
                'verbose_name_plural': '棚卸調整',
                'db_table': 'stocktake_adjustments',
            },
        ),
        migrations.CreateModel(
            name='StocktakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=30, unique=True, verbose_name='棚卸番号')),
                ('stocktake_type', models.CharField(choices=[('full', '全数棚卸'), ('cycle', '循環棚卸')], max_length=20, verbose_name='種別')),
                ('status', models.CharField(choices=[('planning', '計画中'), ('counting', 'カウント中'), ('review', '差異確認中'), ('completed', '完了'), ('cancelled', '取消')], default='planning', max_length=20, verbose_name='ステータス')),
                ('planned_at', models.DateField(verbose_name='棚卸予定日')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('is_locked', models.BooleanField(default=False, help_text='全数棚卸の間に入出庫をロックする想定のフラグ（MVP では値の保持のみ。他の在庫変動画面では未参照）', verbose_name='入出庫ロック中')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, help_text='循環棚卸のときの対象エリア（全数棚卸では空）', null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.area', verbose_name='対象エリア')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse', verbose_name='倉庫')),
            ],
            options={
                'verbose_name': '棚卸セッション',
                'verbose_name_plural': '棚卸セッション',
                'db_table': 'stocktake_sessions',
            },
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stocktakesession', verbose_name='棚卸セッション'),
        ),
        migrations.AddIndex(
            model_name='stocktakesession',
            index=models.Index(fields=['status'], name='idx_stocktake_sessions_st'),
        ),
        migrations.AddIndex(
            model_name='stocktakesession',
            index=models.Index(fields=['planned_at'], name='idx_stocktake_sessions_at'),
        ),
        migrations.AddIndex(
            model_name='stocktakeitem',
            index=models.Index(fields=['status'], name='idx_stocktake_items_status'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeitem',
            constraint=models.UniqueConstraint(fields=('session', 'location', 'sku'), name='uk_stocktake_items_session_location_sku'),
        ),
    ]
