# Generated by Django 5.2.14 on 2026-05-21 09:55

from django.db import migrations, models


def backfill_first_received_at(apps, schema_editor):
    """既存の StockBalance は created_at を first_received_at として埋める。

    過去履歴（StockMovement）から「最後に 0→正 へ切り替わった瞬間」を厳密に
    遡る方が正確だが、運用上の支障は無いので created_at で近似する。
    """
    StockBalance = apps.get_model('stock', 'StockBalance')
    StockBalance.objects.filter(first_received_at__isnull=True).update(
        first_received_at=models.F('created_at')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stocktakeitem_stocktakeadjustment_stocktakesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbalance',
            name='first_received_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='quantity が 0 → 正に切り替わった時刻。FIFO 引き当ての並び替えに使う。', null=True, verbose_name='現在在庫の最古入荷日時'),
        ),
        migrations.RunPython(backfill_first_received_at, migrations.RunPython.noop),
    ]
