# Generated by Django 5.2.14 on 2026-05-30 10:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0005_remap_inboundorder_status'),
        ('masters', '0007_rename_storage_areas_to_agv'),
        ('stock', '0005_add_first_received_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuReorderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_point', models.PositiveIntegerField(help_text='現在庫がこの数を下回ったらアラートを出す', verbose_name='発注点')),
                ('reorder_qty', models.PositiveIntegerField(help_text='バイヤーへの推奨発注数（参考値）', validators=[django.core.validators.MinValueValidator(1)], verbose_name='推奨発注数')),
                ('safety_stock', models.PositiveIntegerField(default=0, help_text='安全在庫数（reorder_point の算出基準）', verbose_name='安全在庫')),
                ('auto_order', models.BooleanField(default=False, help_text='True で発注点到達時に入荷指示を自動生成（運用は手動承認のため UI 上は無効）', verbose_name='自動発注')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sku_reorder_settings', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.sku', verbose_name='SKU')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse', verbose_name='倉庫')),
            ],
            options={
                'verbose_name': '発注設定',
                'verbose_name_plural': '発注設定',
                'db_table': 'sku_reorder_settings',
            },
        ),
        migrations.CreateModel(
            name='ReorderAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_at_alert', models.IntegerField(verbose_name='発生時在庫数')),
                ('reorder_point_at_alert', models.PositiveIntegerField(verbose_name='発生時発注点')),
                ('recommended_qty', models.PositiveIntegerField(verbose_name='発生時推奨発注数')),
                ('status', models.CharField(choices=[('open', '未対応'), ('ordered', '発注済み'), ('resolved', '入庫済み'), ('ignored', '対応不要')], default='open', max_length=20, verbose_name='ステータス')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解消日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inbound_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorder_alerts', to='inbound.inboundorder', verbose_name='対応した入荷指示')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.sku', verbose_name='SKU')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse', verbose_name='倉庫')),
                ('reorder_setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='stock.skureordersetting', verbose_name='発注設定')),
            ],
            options={
                'verbose_name': '発注アラート',
                'verbose_name_plural': '発注アラート',
                'db_table': 'reorder_alerts',
            },
        ),
        migrations.AddIndex(
            model_name='skureordersetting',
            index=models.Index(fields=['warehouse'], name='idx_sku_reord_set_wh'),
        ),
        migrations.AddIndex(
            model_name='skureordersetting',
            index=models.Index(fields=['is_active'], name='idx_sku_reord_set_active'),
        ),
        migrations.AddConstraint(
            model_name='skureordersetting',
            constraint=models.UniqueConstraint(fields=('sku', 'warehouse'), name='uk_sku_reorder_settings_sku_warehouse'),
        ),
        migrations.AddIndex(
            model_name='reorderalert',
            index=models.Index(fields=['sku'], name='idx_reorder_alerts_sku'),
        ),
        migrations.AddIndex(
            model_name='reorderalert',
            index=models.Index(fields=['warehouse'], name='idx_reorder_alerts_wh'),
        ),
        migrations.AddIndex(
            model_name='reorderalert',
            index=models.Index(fields=['status'], name='idx_reorder_alerts_status'),
        ),
        migrations.AddIndex(
            model_name='reorderalert',
            index=models.Index(fields=['inbound_order'], name='idx_reorder_alerts_io'),
        ),
        migrations.AddIndex(
            model_name='reorderalert',
            index=models.Index(fields=['sku', 'warehouse', 'status'], name='idx_reorder_alerts_sku_wh_st'),
        ),
    ]
