# Generated by Django 5.2.14 on 2026-05-17 11:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('exception', '画面例外エラー'), ('import', '取り込みエラー')], max_length=20, verbose_name='種別')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='発生日時')),
                ('summary', models.CharField(help_text='例外クラス＋メッセージ、または取り込みエラーの要約', max_length=255, verbose_name='概要')),
                ('detail', models.TextField(blank=True, help_text='例外のトレースバック、または取り込みに失敗した行データ', verbose_name='詳細')),
                ('source', models.CharField(blank=True, help_text='例外: リクエストパス / 取り込み: 取り込み元の名称', max_length=255, verbose_name='発生元')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='HTTPメソッド')),
                ('reference', models.CharField(blank=True, help_text='取り込みエラーの対象（OMS注文番号など）', max_length=100, verbose_name='対象')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='対応済み')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='対応日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
            ],
            options={
                'verbose_name': 'エラーログ',
                'verbose_name_plural': 'エラーログ',
                'db_table': 'error_logs',
                'indexes': [models.Index(fields=['-occurred_at'], name='idx_error_logs_occurred'), models.Index(fields=['error_type'], name='idx_error_logs_type'), models.Index(fields=['is_resolved'], name='idx_error_logs_resolved')],
            },
        ),
    ]
