# Generated by Django 5.2.14 on 2026-05-10 06:06
# 手動編集: FK フィールドを設計（docs/Django在庫管理システム.sql）の順序に並び替え

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=20, unique=True, verbose_name='顧客コード')),
                ('customer_name', models.CharField(max_length=100, verbose_name='顧客名')),
                ('customer_type', models.IntegerField(choices=[(1, '法人'), (2, '個人事業主'), (3, '一般個人')], default=1, verbose_name='顧客種別')),
                ('industry_type', models.CharField(blank=True, max_length=50, verbose_name='業種')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_code', models.CharField(max_length=20, unique=True, verbose_name='メーカーコード')),
                ('manufacturer_name', models.CharField(max_length=100, verbose_name='メーカー名')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'メーカー',
                'verbose_name_plural': 'メーカー',
                'db_table': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=20, unique=True, verbose_name='仕入先コード')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='仕入先名')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='担当者')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='メールアドレス')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '仕入先',
                'verbose_name_plural': '仕入先',
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=20, unique=True, verbose_name='倉庫コード')),
                ('warehouse_name', models.CharField(max_length=100, verbose_name='倉庫名')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '倉庫',
                'verbose_name_plural': '倉庫',
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=20, unique=True, verbose_name='カテゴリコード')),
                ('category_name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masters.category', verbose_name='親カテゴリ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='商品コード')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.category', verbose_name='カテゴリ')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.manufacturer', verbose_name='メーカー')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.product', verbose_name='商品')),
                ('sku_code', models.CharField(max_length=50, unique=True, verbose_name='SKUコード')),
                ('jan_code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='JANコード')),
                ('size_info', models.CharField(blank=True, max_length=50, verbose_name='サイズ')),
                ('color_info', models.CharField(blank=True, max_length=50, verbose_name='カラー')),
                ('quantity_per_unit', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='入数（ケース）')),
                ('picking_type', models.CharField(choices=[('total', '種まき方式（AGV/GTP）'), ('order', 'オーダーピッキング（大型・長物）')], default='total', max_length=20, verbose_name='ピッキング種別')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
                'db_table': 'skus',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse', verbose_name='倉庫')),
                ('area_code', models.CharField(max_length=20, verbose_name='エリアコード')),
                ('area_name', models.CharField(blank=True, max_length=100, verbose_name='エリア名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'エリア',
                'verbose_name_plural': 'エリア',
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse', verbose_name='倉庫')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.area', verbose_name='エリア')),
                ('location_code', models.CharField(max_length=30, verbose_name='棚番コード')),
                ('location_name', models.CharField(blank=True, max_length=100, verbose_name='表示名')),
                ('location_type', models.CharField(choices=[('storage', '通常棚'), ('large_item', '大型・長物'), ('staging', '出荷ステージング'), ('crossdock', 'クロスドック'), ('receiving', '入荷エリア')], default='storage', max_length=20, verbose_name='種別')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ロケーション',
                'verbose_name_plural': 'ロケーション',
                'db_table': 'locations',
                'indexes': [models.Index(fields=['location_type'], name='idx_locations_type')],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'location_code'), name='uk_locations_warehouse_code')],
            },
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('warehouse', 'area_code'), name='uk_areas_warehouse_code'),
        ),
    ]
