# Generated by Django 5.2.14 on 2026-05-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='location_code_format',
            field=models.CharField(blank=True, help_text='例: A-00-00-00（0=数字1桁, 9=英数字1文字, 他はリテラル）。空欄なら任意の文字列を許可。', max_length=50, verbose_name='棚番フォーマット'),
        ),
    ]
