# Generated by Django 5.2.14 on 2026-05-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_area_location_code_format'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='location',
            name='idx_locations_type',
        ),
        migrations.RemoveField(
            model_name='area',
            name='location_code_format',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_type',
        ),
        migrations.AddField(
            model_name='area',
            name='location_type',
            field=models.CharField(choices=[('storage', '通常棚'), ('large_item', '大型・長物')], default='storage', max_length=20, verbose_name='区分'),
        ),
    ]
