# Generated by Django 5.2.14 on 2026-05-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_remove_location_idx_locations_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'category_code'], 'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリ'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='カテゴリ名（英語）'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_leaf',
            field=models.BooleanField(default=False, verbose_name='末端カテゴリ'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=10, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.CharField(max_length=30, unique=True, verbose_name='カテゴリコード'),
        ),
    ]
