# Generated by Django 5.2.14 on 2026-05-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_category_options_category_category_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name_en',
        ),
        migrations.AlterField(
            model_name='category',
            name='is_leaf',
            field=models.BooleanField(default=False, verbose_name='商品の登録先'),
        ),
    ]
