# Generated by Django 5.2.14 on 2026-05-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_remove_category_category_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='location_type',
            field=models.CharField(choices=[('storage', 'AGV'), ('large_item', '大型・長物')], default='storage', max_length=20, verbose_name='区分'),
        ),
    ]
