# Generated by Django 5.2.14 on 2026-05-10 06:06
# 手動編集: FK フィールドを設計の順序に並び替え

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_order_code', models.CharField(max_length=30, unique=True, verbose_name='入荷指示番号')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse', verbose_name='倉庫')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier', verbose_name='仕入先')),
                ('status', models.CharField(choices=[('pending', '入荷待ち'), ('arrived', '到着済み'), ('receiving', '入荷中'), ('putaway', '格納待ち'), ('completed', '完了'), ('cancelled', '取消')], default='pending', max_length=20, verbose_name='ステータス')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='入荷予定日')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='到着確認日時')),
                ('purchase_order_code', models.CharField(blank=True, max_length=50, verbose_name='SCMラベル発注番号')),
                ('supplier_delivery_note_code', models.CharField(blank=True, max_length=50, verbose_name='仕入先納品書番号')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='入荷完了日時')),
                ('source_type', models.CharField(choices=[('asn', 'ASN自動連携'), ('manual', '手動登録'), ('reorder_alert', '発注アラート起点'), ('return', '返品')], default='asn', max_length=20, verbose_name='入荷元種別')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '入荷指示',
                'verbose_name_plural': '入荷指示',
                'db_table': 'inbound_orders',
            },
        ),
        migrations.CreateModel(
            name='InboundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inbound.inboundorder', verbose_name='入荷指示')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.sku', verbose_name='SKU')),
                ('quantity_expected', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='予定入荷数')),
                ('quantity_received', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='実入荷数')),
                ('is_crossdock', models.BooleanField(default=False, help_text='true=入荷後そのまま出荷エリアへ（棚入れスキップ）', verbose_name='クロスドック')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '入荷指示明細',
                'verbose_name_plural': '入荷指示明細',
                'db_table': 'inbound_order_items',
            },
        ),
        migrations.CreateModel(
            name='InboundReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inbound.inboundorderitem', verbose_name='入荷指示明細')),
                ('location', models.ForeignKey(blank=True, help_text='検品時はNULL、格納完了時に更新', null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.location', verbose_name='格納先ロケーション')),
                ('quantity_expected', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='予定入荷数')),
                ('quantity_received', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='実入荷数')),
                ('discrepancy_type', models.CharField(choices=[('none', '差異なし'), ('shortage', '数量不足'), ('excess', '数量超過'), ('damaged', '破損')], default='none', max_length=20, verbose_name='差異種別')),
                ('discrepancy_note', models.TextField(blank=True, verbose_name='差異理由')),
                ('stock_movement', models.ForeignKey(blank=True, help_text='damaged の場合は NULL（入庫しないため）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stockmovement', verbose_name='紐づく入庫履歴')),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspected_receipts', to=settings.AUTH_USER_MODEL, verbose_name='検品担当者')),
                ('inspected_at', models.DateTimeField(auto_now_add=True, verbose_name='検品完了日時')),
                ('putaway_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_receipts', to=settings.AUTH_USER_MODEL, verbose_name='棚入れ担当者')),
                ('putaway_at', models.DateTimeField(blank=True, null=True, verbose_name='棚入れ完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '入荷検品結果',
                'verbose_name_plural': '入荷検品結果',
                'db_table': 'inbound_receipts',
            },
        ),
        migrations.AddIndex(
            model_name='inboundorder',
            index=models.Index(fields=['status'], name='idx_inbound_orders_status'),
        ),
        migrations.AddIndex(
            model_name='inboundorder',
            index=models.Index(fields=['expected_date'], name='idx_inbound_orders_expected'),
        ),
        migrations.AddConstraint(
            model_name='inboundorderitem',
            constraint=models.UniqueConstraint(fields=('inbound_order', 'sku'), name='uk_inbound_order_items_order_sku'),
        ),
    ]
