# Generated by Django 5.2.14 on 2026-05-16 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundreceipt',
            name='quantity_defective',
            field=models.IntegerField(default=0, help_text='破損・汚損などで在庫対象外となる数。理由は discrepancy_note に記録。', validators=[django.core.validators.MinValueValidator(0)], verbose_name='不良品数'),
        ),
        migrations.AlterField(
            model_name='inboundreceipt',
            name='quantity_received',
            field=models.IntegerField(help_text='検品した入荷総数（良品＋不良品）。', validators=[django.core.validators.MinValueValidator(0)], verbose_name='実入荷数'),
        ),
    ]
