# Generated by Django 5.2.14 on 2026-05-16 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0002_inboundreceipt_quantity_defective_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundorder',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作業開始日時'),
        ),
        migrations.AddField(
            model_name='inboundorder',
            name='in_progress_by',
            field=models.ForeignKey(blank=True, help_text='受入れ・検品の作業中の担当者。NULL=作業中でない（開始で設定、完了で解除）。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_orders_in_progress', to=settings.AUTH_USER_MODEL, verbose_name='作業担当者'),
        ),
    ]
