# Generated by Django 5.2.14 on 2026-05-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0003_inboundorder_in_progress_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundorder',
            name='status',
            field=models.CharField(choices=[('receiving_wait', '受入れ作業待ち'), ('inspection_wait', '検品作業待ち'), ('putaway_wait', '棚入れ作業待ち'), ('completed', '入荷完了'), ('cancelled', '取消')], default='receiving_wait', max_length=20, verbose_name='ステータス'),
        ),
    ]
