# Generated by Django 5.2.14 on 2026-07-28 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0005_remap_inboundorder_status'),
        ('masters', '0007_rename_storage_areas_to_agv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inboundorder',
            index=models.Index(fields=['status', '-created_at'], name='idx_io_status_created'),
        ),
    ]
