"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.contrib.messages import constants as message_constants
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env を読み込む
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()
]

# HTTPS ドメインからの POST(ログイン・登録 等)を CSRF で弾かれないよう許可する。
# Django 4 以降は HTTPS では必須。例: DJANGO_CSRF_TRUSTED_ORIGINS=https://example.com,https://www.example.com
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms',  # FORM_RENDERER='TemplatesSetting' で標準ウィジェットを APP_DIRS から解決させる
    # Third-party
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    # WMS apps
    'accounts',
    'core',
    'masters',
    'stock',
    'inbound',
    'outbound',
    'api',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CorsMiddleware は「レスポンスを生成する他のミドルウェア」より上に置く必要がある。
    # WhiteNoise / CommonMiddleware の前に置くことで、これらが生成するレスポンスにも
    # CORS ヘッダを付与できる（django-cors-headers 公式ドキュメントの推奨配置）。
    'corsheaders.middleware.CorsMiddleware',
    # WhiteNoise は SecurityMiddleware の直後に置く（本番で静的ファイルを配信する）
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # ハンディ作業者は PC 画面にアクセスできない（認証後に判定）
    'accounts.middleware.HandheldOnlyMiddleware',
    # 画面で発生した未処理例外を ErrorLog に記録する
    'core.middleware.ErrorLogMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'masters.context_processors.current_warehouse',
                'accounts.context_processors.user_role',
                'stock.context_processors.open_reorder_alerts',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# カスタムフォームウィジェット (templates/a/widgets/) をプロジェクト TEMPLATES から解決させるため
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['POSTGRES_DB'],
        'USER': os.environ['POSTGRES_USER'],
        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# collectstatic が全アプリ＋STATICFILES_DIRS の静的ファイルを集約する先（本番で配信する単一フォルダ）。
# 生成物なので .gitignore 済み。
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 本番のみ WhiteNoise のハッシュ付き・圧縮配信を使う（キャッシュ最適化）。
# 開発(DEBUG=True)で Manifest 方式にすると collectstatic 前に {% static %} がエラーになるため、
# 開発では標準ストレージのまま（runserver が STATICFILES_DIRS から配信）にする。
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 認証
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/'

# === セッション（ログイン状態）の有効期限 ===
# 業務システムなので「朝ログイン→業務中は連続使用→放置で自動切断」を狙う。
# 期限は 8 時間（業務時間相当）。アクティブ延長で操作するたびに 8 時間後ろに
# ずれるので、連続作業中は切れず、放置した時だけタイムアウトする。
# ブラウザを閉じても期限内ならログイン状態は維持する（近代Webサービスの主流）。
SESSION_COOKIE_AGE = 8 * 60 * 60  # 8時間（秒）
SESSION_SAVE_EVERY_REQUEST = True  # リクエスト毎に期限をリセット（スライディング）
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # ブラウザ閉じても継続（明示）

# Django messages タグを Bootstrap alert のクラス名に合わせる
MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}


# === 本番（DEBUG=False）でのみ有効化するセキュリティ設定 ===
# nginx が HTTPS を終端し、内部は HTTP で gunicorn に転送する構成を前提にする。
# 開発(http://localhost)では無効のままにして手元で困らないようにする。
if not DEBUG:
    # nginx が付ける X-Forwarded-Proto ヘッダで「元リクエストが HTTPS だった」ことを判定する。
    # これが無いと SSL リダイレクトが無限ループしたり secure cookie が送られない。
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # http:// で来たアクセスを https:// へ自動転送する
    SECURE_SSL_REDIRECT = True
    # セッション/CSRF cookie は HTTPS のときだけ送信する（盗聴によるセッション乗っ取り対策）
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS: ブラウザに一定期間 HTTPS を強制させる。まずは 1 日。安定後に伸ばす（例: 31536000=1年）。
    SECURE_HSTS_SECONDS = 86400
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# === REST Framework / OpenAPI (drf-spectacular) ===
# EC サイト連携用の API を提供するため DRF を導入。Swagger UI で API 仕様を公開する。
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': '倉庫管理システム API',
    'DESCRIPTION': 'EC サイト連携用の API（商品マスタ同期・在庫照会・出荷指示作成）。'
                   '詳細は integration/api_spec.md を参照。',
    'VERSION': '0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# === CORS（EC frontend からの API 呼び出しを許可） ===
# 本番は環境変数 DJANGO_CORS_ALLOWED_ORIGINS で許可オリジンを指定する。
# 例: DJANGO_CORS_ALLOWED_ORIGINS=https://ec.komaki-wms.com,https://shop.example.com
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get('DJANGO_CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()
]

# 開発時（DEBUG=True）は localhost で動く Vite / CRA のデフォルトポートを許可する。
# Vite=5173, Create React App=3000 が典型的なデフォルト。
if DEBUG:
    CORS_ALLOWED_ORIGINS += [
        'http://localhost:5173',
        'http://localhost:3000',
        'http://127.0.0.1:5173',
        'http://127.0.0.1:3000',
    ]

# Cookie / 認証情報を伴うリクエストを許可するかどうか。
# MVP では API キー認証のみで Cookie を使わないため False のまま（デフォルト）。
# JWT を Cookie に保存する設計に変更したら True にする。
# CORS_ALLOW_CREDENTIALS = False
